module.exports = {
  CHANGE_USERNAME: 'CHANGE_USERNAME',
  CHANGE_NUMBER: 'CHANGE_NUMBER',
  SET_APP_USER_DATA: 'SET_APP_USER_DATA',
  SET_DROPDOWN_VALUES: 'SET_DROPDOWN_VALUES',
  SET_PART_DATA: 'SET_PART_DATA',
  SET_PART_DETAILS_DATA:'SET_PART_DETAILS_DATA',
  SET_PRODUCT_GUIDE:'SET_PRODUCT_GUIDE',
  SET_SLIDING_IMAGES:'SET_SLIDING_IMAGES',
  SET_FAQ:'SET_FAQ',
  SET_APP_LANGUAGE:'SET_APP_LANGUAGE',

  SET_BRAKING_NEWS_DATA:'SET_BRAKING_NEWS_DATA',
  SET_BRAKING_NEWS_CATEGORIES:'SET_BRAKING_NEWS_CATEGORIES',

  SET_VIDEO_DATA:'SET_VIDEO_DATA'
};
